In [2]:
import pandas as pd

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Student_Marks.csv to Student_Marks.csv

In [4]:
data = {
    "Name": ["Anu", "Ravi", "Priya", "Kiran", "Sneha"],
    "Maths": [85, 78, 92, 67, 88],
    "Science": [90, 82, 89, 72, 91],
    "English": [80, 75, 95, 70, 85]
}

df = pd.DataFrame(data)

df

    Name  Maths  Science  English
0    Anu     85       90       80
1   Ravi     78       82       75
2  Priya     92       89       95
3  Kiran     67       72       70
4  Sneha     88       91       85

In [5]:
def function_name(parameters):
    # calculation
    return result

In [6]:
def add(a, b):
    return a + b

In [7]:
result = add(10, 20)
print(result)

30

In [8]:
def calculate_mean(values):
    return sum(values) / len(values)

In [9]:
marks = [85, 90, 80]

mean = calculate_mean(marks)

print("Mean:", mean)

Mean: 85.0

In [10]:
calculate_mean(marks)

85.0

In [29]:
values = [10, 20, 30, 40, 50]

print(sum(values))

150

In [30]:
values = [10, 20, 30, 40, 50]

print(len(values))

5

In [31]:
values = [10, 20, 30, 40, 50]

mean = sum(values) / len(values)

print(mean)

30.0

In [15]:
def find_maximum(values):
    return max(values)

In [16]:
marks = [85, 90, 80]

maximum = find_maximum(marks)

print("Maximum:", maximum)

Maximum: 90

In [17]:
def find_minimum(values):
    return min(values)

In [18]:
marks = [85, 90, 80]

minimum = find_minimum(marks)

print("Minimum:", minimum)

Minimum: 80

In [19]:
def calculate_percentage(marks, total_marks):
    return (sum(marks) / total_marks) * 100

In [20]:
marks = [85, 90, 80]

percentage = calculate_percentage(marks, 300)

print("Percentage:", percentage)

Percentage: 85.0

In [21]:
def calculate_grade(percentage):
    if percentage >= 90:
        return "A+"
    elif percentage >= 80:
        return "A"
    elif percentage >= 70:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 50:
        return "D"
    else:
        return "F"

In [22]:
df["Total"] = df[["Maths", "Science", "English"]].sum(axis=1)

df["Mean"] = df[["Maths", "Science", "English"]].mean(axis=1)

df["Percentage"] = df["Total"].apply(
    lambda x: calculate_percentage([x], 300)
)

df["Grade"] = df["Percentage"].apply(calculate_grade)

df

    Name  Maths  Science  English  Total       Mean  Percentage Grade
0    Anu     85       90       80    255  85.000000   85.000000     A
1   Ravi     78       82       75    235  78.333333   78.333333     B
2  Priya     92       89       95    276  92.000000   92.000000    A+
3  Kiran     67       72       70    209  69.666667   69.666667     C
4  Sneha     88       91       85    264  88.000000   88.000000     A

In [23]:
all_marks = df[["Maths", "Science", "English"]].values.flatten()

maximum = find_maximum(all_marks)
minimum = find_minimum(all_marks)

print("Maximum Mark:", maximum)
print("Minimum Mark:", minimum)

Maximum Mark: 95
Minimum Mark: 67

In [24]:
math_mean = calculate_mean(df["Maths"].tolist())
science_mean = calculate_mean(df["Science"].tolist())
english_mean = calculate_mean(df["English"].tolist())

print("Maths Mean:", math_mean)
print("Science Mean:", science_mean)
print("English Mean:", english_mean)

Maths Mean: 82.0
Science Mean: 84.8
English Mean: 81.0

In [26]:
def calculate_mean(values):
    return sum(values) / len(values)

numbers = [10, 20, 30, 40, 50]

result = calculate_mean(numbers)

print(result)

30.0

In [27]:
def calculate_mean(values):
    return sum(values) / len(values)


def find_maximum(values):
    return max(values)


def find_minimum(values):
    return min(values)


def calculate_percentage(marks, total_marks):
    return (sum(marks) / total_marks) * 100


def calculate_grade(percentage):
    if percentage >= 90:
        return "A+"
    elif percentage >= 80:
        return "A"
    elif percentage >= 70:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 50:
        return "D"
    else:
        return "F"

In [28]:
marks = [85, 90, 80]

mean = calculate_mean(marks)
maximum = find_maximum(marks)
minimum = find_minimum(marks)
percentage = calculate_percentage(marks, 300)
grade = calculate_grade(percentage)

print("Marks:", marks)
print("Mean:", mean)
print("Maximum:", maximum)
print("Minimum:", minimum)
print("Percentage:", percentage)
print("Grade:", grade)

Marks: [85, 90, 80]
Mean: 85.0
Maximum: 90
Minimum: 80
Percentage: 85.0
Grade: A

In [ ]:
# Functions for Reusable Data Tasks

## Objective
To create reusable Python functions for calculations, data transformation, and simple statistical operations.

## Functions Used

1. calculate_mean() - Calculates the mean of values.
2. find_maximum() - Finds the maximum value.
3. find_minimum() - Finds the minimum value.
4. calculate_percentage() - Calculates percentage.
5. calculate_grade() - Assigns a grade based on percentage.

## Dataset
Student Marks Dataset containing Maths, Science and English marks.

## Conclusion
Functions make Python programs more organized, reusable and readable.
Using parameters and return values allows the same logic to be reused for different data.